### ISSUE TITLE
Preview build broken

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-cognitive#10]
Discovered when creating #8 

Netlify previews are working on most repos [eg](https://github.com/w3c/wai-teach-advocate-overview/pull/7)

Here is the documentation that we have from Eric:
    https://wai-website-theme.netlify.app/overview/
(Note: One section is out of date: "Publication of the WAI Website" https://wai-website-theme.netlify.app/technical/publication/ )

**Comment by slhenry** [comment]
all fixed now! https://deploy-preview-15--wai-cognitive.netlify.app/cognitive/
