### ISSUE TITLE
Bad front matter

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-cognitive#11]
Get this build error

```
YAML Exception reading /home/wsl/wai/wai-website/pages/wai-cognitive/index.md: (<unknown>): mapping values are not allowed in this context at line 15 column 109
```

https://github.com/w3c/wai-cognitive/blob/master/index.md 

Looks like `footer` element name is missing fro line 14 and subsequent content is incomplete

**Comment by slhenry** [comment]
yup. **sorry**! that's what I get for working too many hours in a day

fixed in https://github.com/w3c/wai-cognitive/pull/12/files
